### PR TITLE
chore(package): Add commitizen dependency and script

### PR DESCRIPTION
**Pull request by bookercodes**
Like you requested in #4, I have added `commitizen` as a local dependency. To make it easy to invoke, I also added a small npm script called `commit`.

### CODE REVIEW

**Comment by jspizziri** [comment]
Thanks!

Did you initialize commitizen in the project? It should've added a config object to the package.json. It's typically something like:

``` json
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  }
```

**Comment by bookercodes** [comment]
[I think you've already done that, haven't you?](https://github.com/jspizziri/sequelize-connect/blob/master/package.json#L33)

**Comment by jspizziri** [comment]
Ha, wow. That's weird, I don't remember doing it. Thanks!

**Comment by bookercodes** [comment]
@jspizziri :stuck_out_tongue: 

Thanks for merging this.

**Pull request merged**
